# Generated by Django 3.1.7 on 2022-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Powdered Mushroom', 'Powdered Mushroom'), ('Canned Mushroom', 'Canned Mushroom'), ('Mushroom Mchuzi', 'Mushroom Mchuzi'), ('Fresh Mushroom', 'Fresh Mushroom'), ('Mushroom Juice', 'Mushroom Juice')], max_length=255, null=True),
        ),
    ]
