# Generated by Django 3.1.7 on 2022-08-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(db_column='price', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product'),
        ),
    ]
