# Generated by Django 3.1.7 on 2022-08-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220816_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-date_created',)},
        ),
    ]
