# Generated by Django 3.1.7 on 2022-08-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220821_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
